### ISSUE TITLE
Récupérer les données de l'API bitbucket

### ISSUE THREAD

**Issue by vnctaing** [vnctaing/stethoscope#1]
- [x] Récupérer toutes les PR  (parcours de toutes les pages)
  - OPEN : a priori non pour l’instant, pas toutes les infos nécessaires pour les métriques qu’on souhaite dans l’étape 1
  - MERGED : oui
  - DECLINED : non
- [x] Récupérer tous les commentaires
- [x] Récupérer le temps de merge
- [x] Récupérer le nombre de tag
- [x] Récupérer le nombre de lignes de diff

**Comment by zerbusdetroy** [comment]
#20
